// import Hero from 'next/hero'
import Nav from '@/components/nav'
import Head from 'next/head'
import Hero from'./heromain' 
import Allhotel from './allhotel'  
import Services from './Services'
import Room from './room'
import Save from './save'
import About from './About'



export default function Home() {
  return (
    <>
   <Head>
<title>Alraha hotel</title>
<meta name="description"content="Generated by create next app" />
<meta name="viewport" content="width=device-width,initial-scale=1" />"
<link rel="icon" href="/favicon.ico" />
  </Head>
 <Nav/>
 <Hero/>
 <Allhotel/>
 <Services/>
 <Room/>
 <Save/>
 <About/>


 </>
  )
}
