import { Geist, Geist_Mono , Fustat } from "next/font/google";
import "./globals.css";

const fustat = Fustat({
  variable: "--font-Fustat",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${fustat.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
